import { useState } from 'react'
import GoogleMap from '../components/GoogleMap'
import { calendarDays, mapUrl, saveDateTranslations } from '../data/events'

export default function SaveTheDatePage() {
  const [language, setLanguage] = useState('de')
  const copy = saveDateTranslations[language]
  const saveToCalendar = () => {
    const ics = ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Wedding//EN', 'BEGIN:VEVENT', `UID:${Date.now()}@wedding`, `SUMMARY:${copy.eventSummary}`, 'LOCATION:Milchhaeuschen Koenigswinter', 'DTSTART;VALUE=DATE:20270618', 'DTEND;VALUE=DATE:20270619', 'END:VEVENT', 'END:VCALENDAR'].join('\n')
    const url = URL.createObjectURL(new Blob([ics], { type: 'text/calendar;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'wedding.ics'; link.click(); URL.revokeObjectURL(url)
  }
  return <main className="save-date-page flex min-h-screen items-center justify-center overflow-hidden p-3"><section className="w-full max-w-lg animate-[fade-in_1.2s_ease] rounded-[18px] bg-[#f5f5dc]/90 p-5 text-center shadow-2xl" lang={language}><div className="mb-2 text-right text-sm font-bold"><button type="button" onClick={() => setLanguage('de')} className={language === 'de' ? 'text-[#2d5016]' : ''}>DE</button> <span>|</span> <button type="button" onClick={() => setLanguage('en')} className={language === 'en' ? 'text-[#2d5016]' : ''}>EN</button></div><div className="float-in mx-auto aspect-square w-[min(210px,60vw)] overflow-hidden rounded-full border-4 border-[#8b4513]"><GoogleMap className="h-full w-full" /></div><h1 className="mt-4 font-display text-5xl font-bold text-[#2d5016]">{copy.title}</h1><div className="mt-4 rounded-xl border-2 border-[#8b4513] bg-white p-2"><h2 className="mb-2 font-bold text-[#2d5016]">{copy.month}</h2><div className="mb-1 grid grid-cols-7 text-xs font-bold text-[#5a3b1e]">{copy.weekdays.map(day => <span key={day}>{day}</span>)}</div><div className="calendar-days grid grid-cols-7 text-xs">{calendarDays.map((day, index) => <span key={index} className={day === 18 ? 'rounded-full bg-[#2d5016] px-1 text-white' : ''}>{day}</span>)}</div></div><div className="mt-3 flex gap-2"><button type="button" onClick={saveToCalendar} className="flex-1 rounded-xl bg-[#2d5016] px-3 py-2 text-sm font-bold leading-normal text-white">{copy.save}</button><a href={mapUrl} target="_blank" rel="noreferrer" className="flex flex-1 items-center justify-center rounded-xl bg-[#8b4513] px-3 py-2 text-center text-sm font-bold leading-normal text-white">{copy.map}</a></div><p className="mt-4 whitespace-pre-line border-t border-black/15 pt-3 font-display text-xl leading-snug">{copy.footer}</p><p className="mt-2 font-display text-3xl text-[#6b3e26]">Nina & Mohyiddine</p></section></main>
}
